version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: guard-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: guard-redis
    ports:
      - '6379:6379'
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: guard-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: guardtech-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  mongo_data:
  minio_data:
